version: '3'
services:
  ttrss:
    image: "niflostancu/ttrss"
    ports:
      - "8000:80"
    environment:
      SELF_URL_PATH: 'http://localhost:8000/'
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ttrss
      DB_PASS: ttrss_test_dev123
      DB_NAME: ttrss
  mysql:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'ttrss'
      MYSQL_USER: 'ttrss'
      MYSQL_PASSWORD: 'ttrss_test_dev123'
      MYSQL_ROOT_PASSWORD: 'ttrss_test_dev123'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver_opts:
      type: tmpfs
      device: tmpfs

