version: '3'
services:
  ttrss:
    image: "niflostancu/ttrss"
    ports:
      - "8080:80"
    environment:
      TTRSS_SELF_URL_PATH: 'http://localhost:8000/rss/'
      TTRSS_DB_TYPE: mysql
      TTRSS_DB_HOST: mysql
      TTRSS_DB_PORT: 3306
      TTRSS_DB_USER: ttrss
      TTRSS_DB_PASS: ttrss_test_dev123
      TTRSS_DB_NAME: ttrss
  mysql:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'ttrss'
      MYSQL_USER: 'ttrss'
      MYSQL_PASSWORD: 'ttrss_test_dev123'
      MYSQL_ROOT_PASSWORD: 'ttrss_test_dev123'
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./test-database.sql:/docker-entrypoint-initdb.d/backup.sql

volumes:
  mysql_data:
    driver_opts:
      type: tmpfs
      device: tmpfs

